// <auto-generated />
// 由 app-mcp-codegen 生成（target: csharp），请勿手动修改。
// App：弃用示例（legacy）
// 简介：演示工具级与参数级弃用的生成结果
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading;
using System.Threading.Tasks;

namespace AppMcp.Generated.Legacy;

/// <summary>
/// 按状态列出订单（旧版）
/// </summary>
public sealed record OrdersListParams
{
    /// <summary>
    /// 订单状态
    /// 参数已弃用（inputSchema 中 deprecated: true）；必填属性不能标 [Obsolete]（CS9042）。
    /// </summary>
    [JsonPropertyName("status")]
    public required string Status { get; init; }

    /// <summary>
    /// 页码
    /// 取值范围：≥ 1
    /// </summary>
    [Obsolete("参数已弃用（inputSchema 中 deprecated: true）")]
    [JsonPropertyName("page")]
    public long? Page { get; init; }

    /// <summary>
    /// 最多返回条数
    /// </summary>
    [JsonPropertyName("limit")]
    public long? Limit { get; init; }
}

/// <summary>
/// 过滤条件
/// </summary>
public sealed record OrdersFindFilter
{
    /// <summary>
    /// 关键词
    /// </summary>
    [JsonPropertyName("keyword")]
    public string? Keyword { get; init; }

    /// <summary>
    /// 旧标签
    /// </summary>
    [Obsolete("参数已弃用（inputSchema 中 deprecated: true）")]
    [JsonPropertyName("legacyTag")]
    public string? LegacyTag { get; init; }
}

/// <summary>
/// 按状态查找订单
/// </summary>
public sealed record OrdersFindParams
{
    /// <summary>
    /// 订单状态
    /// </summary>
    [JsonPropertyName("state")]
    public required string State { get; init; }

    /// <summary>
    /// 分页游标
    /// </summary>
    [JsonPropertyName("cursor")]
    public string? Cursor { get; init; }

    /// <summary>
    /// 过滤条件
    /// </summary>
    [JsonPropertyName("filter")]
    public OrdersFindFilter? Filter { get; init; }
}

/// <summary>
/// 清空购物车（旧版）
/// </summary>
public sealed record CartLegacyClearParams
{
}

/// <summary>
/// 弃用示例 的工具实现。每个方法接收已由 Host 按 inputSchema 校验过的参数，
/// 返回值会序列化为 JSON 作为工具结果。
/// </summary>
public interface ILegacyToolHandlers
{
    /// <summary>
    /// 按状态列出订单（旧版）
    ///
    /// 工具 `orders.list`「列出订单」，风险：read
    /// </summary>
    [Obsolete("旧版 \"列表\" 接口 */ 不再维护：$x ${y} \\(z) 'q' <b>&amp; #{w}\n请改用分页更好的新版（改用工具 orders.find；计划于 2027-06-30 移除）")]
    Task<object?> OrdersListAsync(OrdersListParams args, CancellationToken cancellationToken);

    /// <summary>
    /// 按状态查找订单
    ///
    /// 工具 `orders.find`「查找订单」，风险：read
    /// </summary>
    Task<object?> OrdersFindAsync(OrdersFindParams args, CancellationToken cancellationToken);

    /// <summary>
    /// 清空购物车（旧版）
    ///
    /// 工具 `cart.legacyClear`「清空购物车」，风险：write
    /// </summary>
    [Obsolete("改用 cart.clear")]
    Task<object?> CartLegacyClearAsync(CartLegacyClearParams args, CancellationToken cancellationToken);
}

/// <summary>
/// 工具名与分派辅助。
/// </summary>
public static class LegacyTools
{
    /// <summary>
    /// 清单中的全部工具名。
    /// </summary>
    public static readonly IReadOnlyList<string> Names =
    [
        "orders.list",
        "orders.find",
        "cart.legacyClear",
    ];

    /// <summary>
    /// 反序列化参数使用的选项（属性名由特性指定，这里只放宽数字处理）。
    /// </summary>
    public static readonly JsonSerializerOptions JsonOptions = new(JsonSerializerDefaults.Web);

    #pragma warning disable CS0618 // 生成代码需调用已弃用的成员
    /// <summary>
    /// 按工具名把调用分派到对应的 handler。
    /// </summary>
    public static Task<object?> DispatchAsync(ILegacyToolHandlers handlers, string name, JsonElement arguments, CancellationToken cancellationToken = default) =>
        name switch
        {
            "orders.list" => handlers.OrdersListAsync(Parse<OrdersListParams>(arguments), cancellationToken),
            "orders.find" => handlers.OrdersFindAsync(Parse<OrdersFindParams>(arguments), cancellationToken),
            "cart.legacyClear" => handlers.CartLegacyClearAsync(Parse<CartLegacyClearParams>(arguments), cancellationToken),
            _ => throw new ArgumentException($"未知工具：{name}", nameof(name)),
        };
    #pragma warning restore CS0618

    /// <summary>
    /// 把参数 JSON 反序列化为参数类型；缺省或 null 视为空对象。
    /// </summary>
    public static T Parse<T>(JsonElement arguments)
    {
        var value = arguments.ValueKind is JsonValueKind.Undefined or JsonValueKind.Null
            ? JsonSerializer.Deserialize<T>("{}", JsonOptions)
            : arguments.Deserialize<T>(JsonOptions);
        return value ?? throw new JsonException($"无法解析 {typeof(T).Name}");
    }
}
