// <auto-generated />
// 由 app-mcp-codegen 生成（target: windows-app-actions），请勿手动修改。
// App：示例商城（shop）
// 总览：演示用购物商城，可管理待办、浏览商品、操作购物车并结算
//
// App Actions 处理骨架：把 Text 实体解析为参数类型并调用 IShopToolHandlers。
// 需要目标框架 net9.0-windows10.0.26100.0+ 与包标识；COM 注册见 Package.appxmanifest.snippet.xml。
// 启动时（Main）注册：
//   Microsoft.AI.Actions.Helpers.ActionRuntimeFactory.CreateActionRuntime();
//   Microsoft.AI.Actions.Helpers.ActionProviderFactory.RegisterActionProvider<ShopActionProvider, Windows.AI.Actions.Provider.IActionProvider>(new ShopActionProvider(handlers));
#nullable enable

using System;
using System.Collections.Generic;
using System.Globalization;
using System.Runtime.InteropServices;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using Windows.AI.Actions;
using Windows.AI.Actions.Provider;
using Windows.Foundation;

namespace AppMcp.Generated.Shop;

/// <summary>示例商城 的 App Actions 提供者。CLSID 与 ShopActions.json 中的 invocation.clsid 一致。</summary>
[ComVisible(true)]
[Guid("20417D48-159C-4152-A8B8-65C4BCB02557")]
public sealed partial class ShopActionProvider : IActionProvider
{
    private readonly IShopToolHandlers _handlers;

    public ShopActionProvider(IShopToolHandlers handlers) => _handlers = handlers;

    public IAsyncAction InvokeAsync(ActionInvocationContext context) => InvokeCoreAsync(context).AsAsyncAction();

    private async Task InvokeCoreAsync(ActionInvocationContext context)
    {
        var inputs = new Dictionary<string, string>(StringComparer.Ordinal);
        foreach (var named in context.GetInputEntities())
        {
            if (named.Entity is TextActionEntity text)
            {
                inputs[named.Name] = text.Text;
            }
        }

        object? result = context.ActionId switch
        {
            "Shop.CatalogSearch" => await _handlers.CatalogSearchAsync(new CatalogSearchParams { Keyword = Optional(inputs, "keyword"), Category = ParseEnumOrNull<CatalogSearchCategory>(Optional(inputs, "category")), Limit = ParseLongOrNull(Optional(inputs, "limit")), InStock = ParseBoolOrNull(Optional(inputs, "inStock")), MaxPrice = ParseDoubleOrNull(Optional(inputs, "maxPrice")) }, CancellationToken.None),
            "Shop.CartAdd" => await _handlers.CartAddAsync(new CartAddParams { ProductId = Require(inputs, "productId"), Qty = ParseLong(Require(inputs, "qty")), Note = Optional(inputs, "note") }, CancellationToken.None),
            // 风险 destructive：App Actions 没有系统级确认，handler 应在执行前向用户确认。
            "Shop.CartRemoveItem" => await _handlers.CartRemoveItemAsync(new CartRemoveItemParams { ItemId = Require(inputs, "itemId") }, CancellationToken.None),
            // 风险 destructive：App Actions 没有系统级确认，handler 应在执行前向用户确认。
            "Shop.TodosClear" => await _handlers.TodosClearAsync(new TodosClearParams(), CancellationToken.None),
            "Shop.StatsSummary" => await _handlers.StatsSummaryAsync(new StatsSummaryParams { Period = ParseEnumOrNull<StatsSummaryPeriod>(Optional(inputs, "period")) }, CancellationToken.None),
            _ => throw new ArgumentException($"未知 Action：{context.ActionId}"),
        };

        var output = result as string ?? JsonSerializer.Serialize(result, ShopTools.JsonOptions);
        context.SetOutputEntity("response", context.EntityFactory.CreateTextEntity(output));
    }

    private static string Require(Dictionary<string, string> inputs, string name) =>
        inputs.TryGetValue(name, out var value) ? value : throw new ArgumentException($"缺少输入：{name}");

    private static string? Optional(Dictionary<string, string> inputs, string name) =>
        inputs.TryGetValue(name, out var value) && value.Length > 0 ? value : null;

    private static long ParseLong(string value) => long.Parse(value, CultureInfo.InvariantCulture);

    private static long? ParseLongOrNull(string? value) => value is null ? null : ParseLong(value);

    private static double ParseDouble(string value) => double.Parse(value, CultureInfo.InvariantCulture);

    private static double? ParseDoubleOrNull(string? value) => value is null ? null : ParseDouble(value);

    private static bool ParseBool(string value) => bool.Parse(value);

    private static bool? ParseBoolOrNull(string? value) => value is null ? null : ParseBool(value);

    private static T ParseEnum<T>(string value) where T : struct, Enum =>
        JsonSerializer.Deserialize<T>(JsonSerializer.Serialize(value));

    private static T? ParseEnumOrNull<T>(string? value) where T : struct, Enum =>
        value is null ? null : ParseEnum<T>(value);
}
