// <auto-generated />
// 由 app-mcp-codegen 生成（target: csharp），请勿手动修改。
// App：示例商城（shop）
// 总览：演示用购物商城，可管理待办、浏览商品、操作购物车并结算
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading;
using System.Threading.Tasks;

namespace AppMcp.Generated.Shop;

/// <summary>
/// 商品分类
/// </summary>
[JsonConverter(typeof(JsonStringEnumConverter<CatalogSearchCategory>))]
public enum CatalogSearchCategory
{
    [JsonStringEnumMemberName("electronics")] Electronics,
    [JsonStringEnumMemberName("home-goods")] HomeGoods,
    [JsonStringEnumMemberName("food")] Food,
}

/// <summary>
/// 按关键词搜索商品，返回商品 ID、名称、价格
/// </summary>
public sealed record CatalogSearchParams
{
    /// <summary>
    /// 商品名或分类，如“耳机”
    /// </summary>
    [JsonPropertyName("keyword")]
    public string? Keyword { get; init; }

    /// <summary>
    /// 商品分类
    /// </summary>
    [JsonPropertyName("category")]
    public CatalogSearchCategory? Category { get; init; }

    /// <summary>
    /// 最多返回条数
    /// 取值范围：≥ 1，≤ 100；默认值：20
    /// </summary>
    [JsonPropertyName("limit")]
    public long? Limit { get; init; }

    /// <summary>
    /// 只看有货
    /// </summary>
    [JsonPropertyName("inStock")]
    public bool? InStock { get; init; }

    /// <summary>
    /// 价格上限（元）
    /// 取值范围：&gt; 0
    /// </summary>
    [JsonPropertyName("maxPrice")]
    public double? MaxPrice { get; init; }
}

/// <summary>
/// 把商品加入购物车
/// </summary>
public sealed record CartAddParams
{
    /// <summary>
    /// 商品 ID
    /// </summary>
    [JsonPropertyName("productId")]
    public required string ProductId { get; init; }

    /// <summary>
    /// 数量
    /// 取值范围：≥ 1
    /// </summary>
    [JsonPropertyName("qty")]
    public required long Qty { get; init; }

    /// <summary>
    /// 备注，可为 null
    /// </summary>
    [JsonPropertyName("note")]
    public string? Note { get; init; }
}

/// <summary>
/// 从购物车移除一个条目
/// </summary>
public sealed record CartRemoveItemParams
{
    [JsonPropertyName("itemId")]
    public required string ItemId { get; init; }
}

/// <summary>
/// 配送方式
/// </summary>
[JsonConverter(typeof(JsonStringEnumConverter<CartCheckoutShippingMethod>))]
public enum CartCheckoutShippingMethod
{
    [JsonStringEnumMemberName("standard")] Standard,
    [JsonStringEnumMemberName("express")] Express,
}

/// <summary>
/// 配送选项
/// </summary>
public sealed record CartCheckoutShipping
{
    /// <summary>
    /// 配送方式
    /// </summary>
    [JsonPropertyName("method")]
    public required CartCheckoutShippingMethod Method { get; init; }

    /// <summary>
    /// 最早送达时间
    /// 格式：date-time
    /// </summary>
    [JsonPropertyName("deliverAfter")]
    public string? DeliverAfter { get; init; }
}

public sealed record CartCheckoutItemsItem
{
    [JsonPropertyName("itemId")]
    public required string ItemId { get; init; }

    /// <summary>
    /// 取值范围：≥ 1
    /// </summary>
    [JsonPropertyName("qty")]
    public long? Qty { get; init; }
}

/// <summary>
/// 提交订单并支付
/// </summary>
public sealed record CartCheckoutParams
{
    /// <summary>
    /// 收货地址 ID
    /// </summary>
    [JsonPropertyName("addressId")]
    public required string AddressId { get; init; }

    /// <summary>
    /// 优惠码
    /// </summary>
    [JsonPropertyName("coupon")]
    public string? Coupon { get; init; }

    /// <summary>
    /// 配送选项
    /// </summary>
    [JsonPropertyName("shipping")]
    public CartCheckoutShipping? Shipping { get; init; }

    /// <summary>
    /// 只结算这些条目；省略时结算全部
    /// 元素个数：≥ 1
    /// </summary>
    [JsonPropertyName("items")]
    public IReadOnlyList<CartCheckoutItemsItem>? Items { get; init; }

    /// <summary>
    /// 默认值：false
    /// </summary>
    [JsonPropertyName("giftWrap")]
    public bool? GiftWrap { get; init; }
}

/// <summary>
/// 新增一条待办
/// </summary>
public sealed record TodosAddParams
{
    /// <summary>
    /// 待办内容
    /// 长度：1–200
    /// </summary>
    [JsonPropertyName("title")]
    public required string Title { get; init; }

    /// <summary>
    /// 优先级
    /// 可选值：1, 2, 3
    /// </summary>
    [JsonPropertyName("priority")]
    public long? Priority { get; init; }

    /// <summary>
    /// 标签
    /// </summary>
    [JsonPropertyName("tags")]
    public IReadOnlyList<string>? Tags { get; init; }

    /// <summary>
    /// 截止日期
    /// 格式：date
    /// </summary>
    [JsonPropertyName("dueDate")]
    public string? DueDate { get; init; }

    /// <summary>
    /// 分类（属性名是保留字）
    /// </summary>
    [JsonPropertyName("class")]
    public string? Class { get; init; }

    /// <summary>
    /// 属性名含连字符
    /// </summary>
    [JsonPropertyName("is-urgent")]
    public bool? IsUrgent { get; init; }
}

/// <summary>
/// 删除全部已完成的待办
/// </summary>
public sealed record TodosClearParams
{
}

/// <summary>
/// 按条件导出订单
/// </summary>
public sealed record OrdersExportParams
{
    /// <summary>
    /// 筛选条件（任意形式）
    /// 原始 JSON（不支持一般形式的 `oneOf`）
    /// </summary>
    [JsonPropertyName("filter")]
    public JsonElement? Filter { get; init; }

    /// <summary>
    /// 附加标签
    /// </summary>
    [JsonPropertyName("labels")]
    public IReadOnlyDictionary<string, string>? Labels { get; init; }

    /// <summary>
    /// 透传给导出器的任意 JSON
    /// </summary>
    [JsonPropertyName("extra")]
    public JsonElement? Extra { get; init; }

    /// <summary>
    /// 原始 JSON（不支持 `$ref`）
    /// </summary>
    [JsonPropertyName("template")]
    public JsonElement? Template { get; init; }
}

/// <summary>
/// 统计周期
/// </summary>
[JsonConverter(typeof(JsonStringEnumConverter<StatsSummaryPeriod>))]
public enum StatsSummaryPeriod
{
    [JsonStringEnumMemberName("day")] Day,
    [JsonStringEnumMemberName("week")] Week,
    [JsonStringEnumMemberName("month")] Month,
}

/// <summary>
/// 查看销售概览
/// </summary>
public sealed record StatsSummaryParams
{
    /// <summary>
    /// 统计周期
    /// </summary>
    [JsonPropertyName("period")]
    public StatsSummaryPeriod? Period { get; init; }
}

/// <summary>
/// 示例商城 的工具实现。每个方法接收已由 Host 按 inputSchema 校验过的参数，
/// 返回值会序列化为 JSON 作为工具结果。
/// </summary>
public interface IShopToolHandlers
{
    /// <summary>
    /// 按关键词搜索商品，返回商品 ID、名称、价格
    ///
    /// 工具 `catalog.search`「搜索商品」，风险：read
    /// </summary>
    Task<object?> CatalogSearchAsync(CatalogSearchParams args, CancellationToken cancellationToken);

    /// <summary>
    /// 把商品加入购物车
    ///
    /// 工具 `cart.add`「加入购物车」，风险：write
    /// </summary>
    Task<object?> CartAddAsync(CartAddParams args, CancellationToken cancellationToken);

    /// <summary>
    /// 从购物车移除一个条目
    ///
    /// 工具 `cart.removeItem`「移除购物车条目」，风险：destructive
    /// </summary>
    Task<object?> CartRemoveItemAsync(CartRemoveItemParams args, CancellationToken cancellationToken);

    /// <summary>
    /// 提交订单并支付
    ///
    /// 工具 `cart.checkout`「结算」，风险：payment
    /// </summary>
    Task<object?> CartCheckoutAsync(CartCheckoutParams args, CancellationToken cancellationToken);

    /// <summary>
    /// 新增一条待办
    ///
    /// 工具 `todos.add`「新增待办」，风险：write
    /// </summary>
    Task<object?> TodosAddAsync(TodosAddParams args, CancellationToken cancellationToken);

    /// <summary>
    /// 删除全部已完成的待办
    ///
    /// 工具 `todos.clear`「清空待办」，风险：destructive
    /// </summary>
    Task<object?> TodosClearAsync(TodosClearParams args, CancellationToken cancellationToken);

    /// <summary>
    /// 按条件导出订单
    ///
    /// 工具 `orders.export`「导出订单」，风险：write
    /// </summary>
    Task<object?> OrdersExportAsync(OrdersExportParams args, CancellationToken cancellationToken);

    /// <summary>
    /// 查看销售概览
    ///
    /// 工具 `stats.summary`「销售概览」，风险：read
    /// </summary>
    Task<object?> StatsSummaryAsync(StatsSummaryParams args, CancellationToken cancellationToken);
}

/// <summary>
/// 工具名与分派辅助。
/// </summary>
public static class ShopTools
{
    /// <summary>
    /// 清单中的全部工具名。
    /// </summary>
    public static readonly IReadOnlyList<string> Names =
    [
        "catalog.search",
        "cart.add",
        "cart.removeItem",
        "cart.checkout",
        "todos.add",
        "todos.clear",
        "orders.export",
        "stats.summary",
    ];

    /// <summary>
    /// 反序列化参数使用的选项（属性名由特性指定，这里只放宽数字处理）。
    /// </summary>
    public static readonly JsonSerializerOptions JsonOptions = new(JsonSerializerDefaults.Web);

    /// <summary>
    /// 按工具名把调用分派到对应的 handler。
    /// </summary>
    public static Task<object?> DispatchAsync(IShopToolHandlers handlers, string name, JsonElement arguments, CancellationToken cancellationToken = default) =>
        name switch
        {
            "catalog.search" => handlers.CatalogSearchAsync(Parse<CatalogSearchParams>(arguments), cancellationToken),
            "cart.add" => handlers.CartAddAsync(Parse<CartAddParams>(arguments), cancellationToken),
            "cart.removeItem" => handlers.CartRemoveItemAsync(Parse<CartRemoveItemParams>(arguments), cancellationToken),
            "cart.checkout" => handlers.CartCheckoutAsync(Parse<CartCheckoutParams>(arguments), cancellationToken),
            "todos.add" => handlers.TodosAddAsync(Parse<TodosAddParams>(arguments), cancellationToken),
            "todos.clear" => handlers.TodosClearAsync(Parse<TodosClearParams>(arguments), cancellationToken),
            "orders.export" => handlers.OrdersExportAsync(Parse<OrdersExportParams>(arguments), cancellationToken),
            "stats.summary" => handlers.StatsSummaryAsync(Parse<StatsSummaryParams>(arguments), cancellationToken),
            _ => throw new ArgumentException($"未知工具：{name}", nameof(name)),
        };

    /// <summary>
    /// 把参数 JSON 反序列化为参数类型；缺省或 null 视为空对象。
    /// </summary>
    public static T Parse<T>(JsonElement arguments)
    {
        var value = arguments.ValueKind is JsonValueKind.Undefined or JsonValueKind.Null
            ? JsonSerializer.Deserialize<T>("{}", JsonOptions)
            : arguments.Deserialize<T>(JsonOptions);
        return value ?? throw new JsonException($"无法解析 {typeof(T).Name}");
    }
}
