// <auto-generated />
// 由 app-mcp-codegen 生成（target: windows-app-actions），请勿手动修改。
// App：弃用示例（legacy）
// 简介：演示工具级与参数级弃用的生成结果
//
// App Actions 处理骨架：把 Text 实体解析为参数类型并调用 ILegacyToolHandlers。
// 需要目标框架 net9.0-windows10.0.26100.0+ 与包标识；COM 注册见 Package.appxmanifest.snippet.xml。
// 启动时（Main）注册：
//   Microsoft.AI.Actions.Helpers.ActionRuntimeFactory.CreateActionRuntime();
//   Microsoft.AI.Actions.Helpers.ActionProviderFactory.RegisterActionProvider<LegacyActionProvider, Windows.AI.Actions.Provider.IActionProvider>(new LegacyActionProvider(handlers));
#nullable enable

using System;
using System.Collections.Generic;
using System.Globalization;
using System.Runtime.InteropServices;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using Windows.AI.Actions;
using Windows.AI.Actions.Provider;
using Windows.Foundation;

namespace AppMcp.Generated.Legacy;

/// <summary>弃用示例 的 App Actions 提供者。CLSID 与 LegacyActions.json 中的 invocation.clsid 一致。</summary>
[ComVisible(true)]
[Guid("D4CEEC76-3502-4597-8B6C-2CCFA3EF1C6A")]
public sealed partial class LegacyActionProvider : IActionProvider
{
    private readonly ILegacyToolHandlers _handlers;

    public LegacyActionProvider(ILegacyToolHandlers handlers) => _handlers = handlers;

    public IAsyncAction InvokeAsync(ActionInvocationContext context) => InvokeCoreAsync(context).AsAsyncAction();

    private async Task InvokeCoreAsync(ActionInvocationContext context)
    {
        var inputs = new Dictionary<string, string>(StringComparer.Ordinal);
        foreach (var named in context.GetInputEntities())
        {
            if (named.Entity is TextActionEntity text)
            {
                inputs[named.Name] = text.Text;
            }
        }

        #pragma warning disable CS0618 // 生成代码需调用已弃用的成员
        object? result = context.ActionId switch
        {
            // 已弃用：旧版 "列表" 接口 */ 不再维护：$x ${y} \(z) 'q' <b>&amp; #{w}
            // 请改用分页更好的新版（改用工具 orders.find；计划于 2027-06-30 移除）
            "Legacy.OrdersList" => await _handlers.OrdersListAsync(new OrdersListParams { Status = Require(inputs, "status"), Page = ParseLongOrNull(Optional(inputs, "page")), Limit = ParseLongOrNull(Optional(inputs, "limit")) }, CancellationToken.None),
            // 已弃用：改用 cart.clear
            "Legacy.CartLegacyClear" => await _handlers.CartLegacyClearAsync(new CartLegacyClearParams(), CancellationToken.None),
            _ => throw new ArgumentException($"未知 Action：{context.ActionId}"),
        };
        #pragma warning restore CS0618

        var output = result as string ?? JsonSerializer.Serialize(result, LegacyTools.JsonOptions);
        context.SetOutputEntity("response", context.EntityFactory.CreateTextEntity(output));
    }

    private static string Require(Dictionary<string, string> inputs, string name) =>
        inputs.TryGetValue(name, out var value) ? value : throw new ArgumentException($"缺少输入：{name}");

    private static string? Optional(Dictionary<string, string> inputs, string name) =>
        inputs.TryGetValue(name, out var value) && value.Length > 0 ? value : null;

    private static long ParseLong(string value) => long.Parse(value, CultureInfo.InvariantCulture);

    private static long? ParseLongOrNull(string? value) => value is null ? null : ParseLong(value);

    private static double ParseDouble(string value) => double.Parse(value, CultureInfo.InvariantCulture);

    private static double? ParseDoubleOrNull(string? value) => value is null ? null : ParseDouble(value);

    private static bool ParseBool(string value) => bool.Parse(value);

    private static bool? ParseBoolOrNull(string? value) => value is null ? null : ParseBool(value);

    private static T ParseEnum<T>(string value) where T : struct, Enum =>
        JsonSerializer.Deserialize<T>(JsonSerializer.Serialize(value));

    private static T? ParseEnumOrNull<T>(string? value) where T : struct, Enum =>
        value is null ? null : ParseEnum<T>(value);
}
